name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test-bot:
    strategy:
      fail-fast: false 
      matrix:
        os:
          - ubuntu-20.04      # Linux (Older LTS)
          - ubuntu-22.04      # Linux (Standard LTS)
          - ubuntu-24.04      # Linux (Newest LTS)
          - macos-14          # Apple Silicon (Sonoma)
          - macos-15          # Intel/Apple Silicon (Sequoia)
          - macos-latest      # macOS 26 Tahoe (The future)
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run brew test-bot --only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup

      - name: Run brew test-bot --only-formulae
        run: |
          # Building 'cmix' for every modern architecture
          # This generates the ARM64 (M1-M5) and x86_64 bottles
          brew test-bot --only-formulae --root-url=https://ghcr.io/v2/${{ github.repository_owner }}/cmix cmix

      - name: Upload bottles as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
