name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04      # Legacy Intel Linux
          - ubuntu-22.04      # Intel Linux
          - ubuntu-24.04      # Modern Linux
          - macos-14          # Apple Silicon
          - macos-15          # Intel/Apple Silicon (Sequoia)
          - macos-latest # Tahoe (Latest)
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run brew test-bot --only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup

      - name: Run brew test-bot --only-formulae
        run: |
          brew test-bot --only-formulae --root-url=https://ghcr.io/v2/${{ github.repository_owner }}/cmix cmix

      - name: Upload bottles as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
