name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:

# This gives your "Build Farm" permission to create and upload Bottles
permissions:
  contents: read
  packages: write

jobs:
  test-bot:
    strategy:
      # If one machine fails, the others keep working!
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-14
          - macos-15
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run brew test-bot --only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup

      - name: Run brew test-bot --only-formulae
        run: |
          # This line forces the robot to look at 'cmix' even if it thinks nothing changed
          brew test-bot --only-formulae --root-url=https://ghcr.io/v2/${{ github.repository_owner }}/cmix cmix

      - name: Upload bottles as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # This saves the pre-compiled "Pills" for you to download
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
